<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>FoggyWeather</AssemblyName>
    <RootNamespace>FoggyWeather</RootNamespace>
    <Version>1.0.0-alpha.33</Version>
    <TargetFramework>net6.0</TargetFramework>
    <Authors>Sakorona</Authors>
    <Description>Adds fog into the world.</Description>
    <MinimumApiVersion>4.0</MinimumApiVersion>
    <UniqueID>knakamura.foggyweather</UniqueID>
    <UpdateKeys>Nexus:00000</UpdateKeys>
    <MinimumApiVersion_Behavior>Update</MinimumApiVersion_Behavior>

    <EnableHarmony>true</EnableHarmony>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="FogType.cs" />
    <Compile Remove="FogWeather.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Leclair.Stardew.ModManifestBuilder" Version="2.1.0" />
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.1.1" />
  </ItemGroup>

  <Import Project="..\TwilightCoreShared\TwilightCoreShared.projitems" Label="Shared" />
  <Import Project="$(SolutionDir)\deploy-mod.targets" />

</Project>