using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TwilightShards.ClimatesOfFerngillRebuild
    public enum WeatherTypes
    {
        None = BaseWeathers.Unset,
        Sunny = BaseWeathers.Sunny,
        Rainy =  BaseWeathers.Rain,
        Snowy = BaseWeathers.Snow,
        Windy = BaseWeathers.Wind,
        Festival = BaseWeathers.Festival,
        Wedding = BaseWeathers.Wedding,
        Stormy = BaseWeathers.Rain | BaseWeathers.Lightning,
        Sunshower = BaseWeathers.Sunny | BaseWeathers.Rain,
        DryLightning = BaseWeathers.Sunny | BaseWeathers.Lightning,
        Blizzard = BaseWeathers.Blizzard | BaseWeathers.Snow,
        WhiteOut = BaseWeathers.WhiteOut | Blizzard,
        Fog = BaseWeathers.Fog | Sunny,
        RainyFog = BaseWeathers.Fog | Rainy,
        SnowyFog = BaseWeathers.Fog | Snowy,
        StormyFog = BaseWeathers.Fog | Stormy,
        DryLightningFog = BaseWeathers.Fog | DryLightning,
        SunshowerFog = BaseWeathers.Fog | Sunshower,
        BlizzardFog = BaseWeathers.Fog | Blizzard,
        WhiteOutFog = BaseWeathers.Fog | WhiteOut,
        BloodRain = BaseWeathers.BloodMoon | BaseWeathers.Rain,
        BloodSnow = BaseWeathers.BloodMoon | BaseWeathers.Snow,
        BloodStorm = BaseWeathers.BloodMoon | Stormy,
        BloodMoon = BaseWeathers.BloodMoon | BaseWeathers.Sunny,
        BloodWind = BaseWeathers.BloodMoon | BaseWeathers.Wind,
        BloodFog = BaseWeathers.BloodMoon | Fog,
        BloodRainFog = BaseWeathers.BloodMoon | RainyFog,
        BloodSnowFog = BaseWeathers.BloodMoon | SnowyFog,
        BloodStormFog = BaseWeathers.BloodMoon | StormyFog,
        BloodDryLightFog = BaseWeathers.BloodMoon | DryLightningFog,
        ThunderFrenzy = BaseWeathers.ThunderFrenzy | Stormy,
        ThunderFrenzyFog = ThunderFrenzy | BaseWeathers.Fog,
        HurricaneRain = Rainy | BaseWeathers.HurricaneRain,
        HurricaneRainFog = HurricaneRain | BaseWeathers.Fog,
        HurricaneThunder = HurricaneRain | ThunderFrenzy,
        HurricaneThunderFog = HurricaneThunder | BaseWeathers.Fog,
        SunnyHeatwave = BaseWeathers.Sunny | BaseWeathers.Heatwave,
        RainyHeatwave =  BaseWeathers.Rain | BaseWeathers.Heatwave,
        SnowyHeatwave = BaseWeathers.Snow | BaseWeathers.Heatwave,
        WindyHeatwave = BaseWeathers.Wind | BaseWeathers.Heatwave,
        FestivalHeatwave = BaseWeathers.Festival | BaseWeathers.Heatwave,
        WeddingHeatwave = BaseWeathers.Wedding | BaseWeathers.Heatwave,
        StormyHeatwave = BaseWeathers.Rain | BaseWeathers.Lightning | BaseWeathers.Heatwave,
        SunshowerHeatwave = BaseWeathers.Sunny | BaseWeathers.Rain | BaseWeathers.Heatwave,
        DryLightningHeatwave = BaseWeathers.Sunny | BaseWeathers.Lightning | BaseWeathers.Heatwave,
        BlizzardHeatwave = BaseWeathers.Blizzard | BaseWeathers.Snow | BaseWeathers.Heatwave,
        WhiteOutHeatwave = BaseWeathers.WhiteOut | Blizzard | BaseWeathers.Heatwave,
        FogHeatwave = BaseWeathers.Fog | Sunny | BaseWeathers.Heatwave,
        RainyFogHeatwave = BaseWeathers.Fog | Rainy | BaseWeathers.Heatwave,
        SnowyFogHeatwave = BaseWeathers.Fog | Snowy | BaseWeathers.Heatwave,
        StormyFogHeatwave = BaseWeathers.Fog | Stormy | BaseWeathers.Heatwave,
        DryLightningFogHeatwave = BaseWeathers.Fog | DryLightning | BaseWeathers.Heatwave,
        SunshowerFogHeatwave = BaseWeathers.Fog | Sunshower | BaseWeathers.Heatwave,
        BlizzardFogHeatwave = BaseWeathers.Fog | Blizzard | BaseWeathers.Heatwave,
        WhiteOutFogHeatwave = BaseWeathers.Fog | WhiteOut | BaseWeathers.Heatwave,
        BloodRainHeatwave = BaseWeathers.BloodMoon | BaseWeathers.Rain | BaseWeathers.Heatwave,
        BloodSnowHeatwave = BaseWeathers.BloodMoon | BaseWeathers.Snow | BaseWeathers.Heatwave,
        BloodStormHeatwave = BaseWeathers.BloodMoon | Stormy | BaseWeathers.Heatwave,
        BloodMoonHeatwave = BaseWeathers.BloodMoon | BaseWeathers.Sunny | BaseWeathers.Heatwave,
        BloodWindHeatwave = BaseWeathers.BloodMoon | BaseWeathers.Wind | BaseWeathers.Heatwave,
        BloodFogHeatwave = BaseWeathers.BloodMoon | Fog | BaseWeathers.Heatwave,
        BloodRainFogHeatwave = BaseWeathers.BloodMoon | RainyFog | BaseWeathers.Heatwave,
        BloodSnowFogHeatwave = BaseWeathers.BloodMoon | SnowyFog | BaseWeathers.Heatwave,
        BloodStormFogHeatwave = BaseWeathers.BloodMoon | StormyFog | BaseWeathers.Heatwave,
        BloodDryLightFogHeatwave = BaseWeathers.BloodMoon | DryLightningFog | BaseWeathers.Heatwave,
        ThunderFrenzyHeatwave = BaseWeathers.ThunderFrenzy | Stormy | BaseWeathers.Heatwave,
        ThunderFrenzyFogHeatwave = ThunderFrenzy | BaseWeathers.Fog | BaseWeathers.Heatwave,
        HurricaneRainHeatwave = Rainy | BaseWeathers.HurricaneRain | BaseWeathers.Heatwave,
        HurricaneRainFogHeatwave = HurricaneRain | BaseWeathers.Fog | BaseWeathers.Heatwave,
        HurricaneThunderHeatwave = HurricaneRain | ThunderFrenzy | BaseWeathers.Heatwave,
        HurricaneThunderFogHeatwave = HurricaneThunder | BaseWeathers.Fog | BaseWeathers.Heatwave,
        SunnyFrost = BaseWeathers.Sunny | BaseWeathers.Frost,
        RainyFrost =  BaseWeathers.Rain | BaseWeathers.Frost,
        SnowyFrost = BaseWeathers.Snow | BaseWeathers.Frost,
        WindyFrost = BaseWeathers.Wind | BaseWeathers.Frost,
        FestivalFrost = BaseWeathers.Festival | BaseWeathers.Frost,
        WeddingFrost = BaseWeathers.Wedding | BaseWeathers.Frost,
        StormyFrost = BaseWeathers.Rain | BaseWeathers.Lightning | BaseWeathers.Frost,
        SunshowerFrost = BaseWeathers.Sunny | BaseWeathers.Rain | BaseWeathers.Frost,
        DryLightningFrost = BaseWeathers.Sunny | BaseWeathers.Lightning | BaseWeathers.Frost,
        BlizzardFrost = BaseWeathers.Blizzard | BaseWeathers.Snow | BaseWeathers.Frost,
        WhiteOutFrost = BaseWeathers.WhiteOut | Blizzard | BaseWeathers.Frost,
        FogFrost = BaseWeathers.Fog | Sunny | BaseWeathers.Frost,
        RainyFogFrost = BaseWeathers.Fog | Rainy | BaseWeathers.Frost,
        SnowyFogFrost = BaseWeathers.Fog | Snowy | BaseWeathers.Frost,
        StormyFogFrost = BaseWeathers.Fog | Stormy | BaseWeathers.Frost,
        DryLightningFogFrost = BaseWeathers.Fog | DryLightning | BaseWeathers.Frost,
        SunshowerFogFrost = BaseWeathers.Fog | Sunshower | BaseWeathers.Frost,
        BlizzardFogFrost = BaseWeathers.Fog | Blizzard | BaseWeathers.Frost,
        WhiteOutFogFrost = BaseWeathers.Fog | WhiteOut | BaseWeathers.Frost,
        BloodRainFrost = BaseWeathers.BloodMoon | BaseWeathers.Rain | BaseWeathers.Frost,
        BloodSnowFrost = BaseWeathers.BloodMoon | BaseWeathers.Snow | BaseWeathers.Frost,
        BloodStormFrost = BaseWeathers.BloodMoon | Stormy | BaseWeathers.Frost,
        BloodMoonFrost = BaseWeathers.BloodMoon | BaseWeathers.Sunny | BaseWeathers.Frost,
        BloodWindFrost = BaseWeathers.BloodMoon | BaseWeathers.Wind | BaseWeathers.Frost,
        BloodFogFrost = BaseWeathers.BloodMoon | Fog | BaseWeathers.Frost,
        BloodRainFogFrost = BaseWeathers.BloodMoon | RainyFog | BaseWeathers.Frost,
        BloodSnowFogFrost = BaseWeathers.BloodMoon | SnowyFog | BaseWeathers.Frost,
        BloodStormFogFrost = BaseWeathers.BloodMoon | StormyFog | BaseWeathers.Frost,
        BloodDryLightFogFrost = BaseWeathers.BloodMoon | DryLightningFog | BaseWeathers.Frost,
        ThunderFrenzyFrost = BaseWeathers.ThunderFrenzy | Stormy | BaseWeathers.Frost,
        ThunderFrenzyFogFrost = ThunderFrenzy | BaseWeathers.Fog | BaseWeathers.Frost,
        HurricaneRainFrost = Rainy | BaseWeathers.HurricaneRain | BaseWeathers.Frost,
        HurricaneRainFogFrost = HurricaneRain | BaseWeathers.Fog | BaseWeathers.Frost,
        HurricaneThunderFrost = HurricaneRain | ThunderFrenzy | BaseWeathers.Frost,
        HurricaneThunderFogFrost = HurricaneThunder | BaseWeathers.Fog | BaseWeathers.Frost
    }
}